### ISSUE TITLE
get Name or service not known when I set authentication_flow_host

### ISSUE THREAD

**Issue by ghorbani-mohammad** [kuzmoyev/google-calendar-simple-api#107] opened 2021-07-26 07:34 UTC
Hi, Thanks for your great library. I want to test Google Calendar API in my Django app. My problem is that when I set authentication_flow_host to my API address (https://api.xxxx.com/v1/test/) I get the error "Name or service not known". How I can solve this problem? thanks in advance.

**Comment by kuzmoyev** [comment] 2021-07-26 07:45
Try removing protocol (`https://`) from from the host

**Comment by ghorbani-mohammad** [comment] 2021-07-26 07:52
Still gives me that error. Do you see any problem in this code?
```
calendar = GoogleCalendar(
        "MYEMAIL@gmail.com",
        authentication_flow_host="api.MYDOMAIN.com/v1/str/test/",
        authentication_flow_port=443,
    )
```

**Comment by kuzmoyev** [comment] 2021-07-26 08:33
Oh, actually I think it has to be a host, not the URL, i.e. `api.MYDOMAIN.com`.

**Comment by ghorbani-mohammad** [comment] 2021-07-26 09:14
That error was solved, but now a new error shows up and saying "**Cannot assign requested address**". It seems trying to create a new server but fails. I run my Django app on a docker container. Is this problem related to docker?



```
/usr/local/lib/python3.9/site-packages/gcsa/google_calendar.py in _get_credentials(token_path, credentials_dir, credentials_file, scopes, save_token, host, port)
    128                 credentials_path = os.path.join(credentials_dir, credentials_file)
    129                 flow = InstalledAppFlow.from_client_secrets_file(credentials_path, scopes)
--> 130                 credentials = flow.run_local_server(host=host, port=port)
    131
    132             if save_token:

/usr/local/lib/python3.9/site-packages/google_auth_oauthlib/flow.py in run_local_server(self, host, port, authorization_prompt_message, success_message, open_browser, redirect_uri_trailing_slash, **kwargs)
    458         # Fail fast if the address is occupied
    459         wsgiref.simple_server.WSGIServer.allow_reuse_address = False
--> 460         local_server = wsgiref.simple_server.make_server(
    461             host, port, wsgi_app, handler_class=_WSGIRequestHandler
    462         )

/usr/local/lib/python3.9/wsgiref/simple_server.py in make_server(host, port, app, server_class, handler_class)
    152 ):
    153     """Create a new WSGI server listening on `host` and `port` for `app`"""
--> 154     server = server_class((host, port), handler_class)
    155     server.set_app(app)
    156     return server

/usr/local/lib/python3.9/socketserver.py in __init__(self, server_address, RequestHandlerClass, bind_and_activate)
    450         if bind_and_activate:
    451             try:
--> 452                 self.server_bind()
    453                 self.server_activate()
    454             except:

/usr/local/lib/python3.9/wsgiref/simple_server.py in server_bind(self)
     48     def server_bind(self):
     49         """Override server_bind to store the server name."""
---> 50         HTTPServer.server_bind(self)
     51         self.setup_environ()
     52

/usr/local/lib/python3.9/http/server.py in server_bind(self)
    136     def server_bind(self):
    137         """Override server_bind to store the server name."""
--> 138         socketserver.TCPServer.server_bind(self)
    139         host, port = self.server_address[:2]
    140         self.server_name = socket.getfqdn(host)

/usr/local/lib/python3.9/socketserver.py in server_bind(self)
    464         if self.allow_reuse_address:
    465             self.socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
--> 466         self.socket.bind(self.server_address)
    467         self.server_address = self.socket.getsockname()
    468

OSError: [Errno 99] Cannot assign requested address
```

**Comment by kuzmoyev** [comment] 2021-07-28 14:50
Have you been able to resolve this? I think it might be caused by the docker.

**Comment by kuzmoyev** [comment] 2021-07-29 15:13
I'll close the issue. If you think this needs more attention, please let me know here.

**Closed by kuzmoyev** 2021-07-29 15:13 UTC
